allowBuilds:
  '@github/keytar': set this to true or false
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  node-pty: true
  protobufjs: true

overrides:
  serialize-javascript: "7.0.5"
  diff: "8.0.3"
  glob: "13.0.6"
  tar-fs: ">=2.1.4"
